### ISSUE TITLE
Cheribuild for freebsd-aarch64

### ISSUE THREAD

**Issue by graymalkin** [CTSRD-CHERI/cheribuild#259]
Hello,

I'm strugling to get `./cheribuild.py freebsd-aarch64` to complete successfully: it's getting hung up on unit tests for bmake.

I'm on a Mac, macOS version 11.6. I've installed the dependencies as described in the README.md. Am I missing something?

Thanks,
Simon

```
[...]
#      test  varquote
--- /Users/simon/cheri/freebsd/contrib/bmake/unit-tests/shell-ksh.exp	2021-11-08 13:10:20.000000000 +0000
+++ shell-ksh.out	2021-11-08 13:11:30.000000000 +0000
@@ -1,4 +1,6 @@
 : normal
-: always
-: ignore errors
-exit status 0
+*** Signal 11 (continuing)
+
+Stop.
+make: stopped in unit-tests
+exit status 1
Failed tests: shell-ksh
*** Error code 1
Stop.
bmake[1]: stopped in /Users/simon/cheri/freebsd/contrib/bmake/unit-tests
*** Error code 1
Stop.
bmake: stopped in /Users/simon/cheri/freebsd/contrib/bmake
Bootstrapping bmake...
Traceback (most recent call last):
  File "/Users/simon/cheri/freebsd/tools/build/make.py", line 249, in <module>
    bmake_binary = bootstrap_bmake(source_root, objdir_prefix)
  File "/Users/simon/cheri/freebsd/tools/build/make.py", line 84, in bootstrap_bmake
    run(["sh", bmake_source_dir / "boot-strap"] + configure_args,
  File "/Users/simon/cheri/freebsd/tools/build/make.py", line 55, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', '/Users/simon/cheri/freebsd/contrib/bmake/boot-strap', '--with-default-sys-path=/Users/simon/cheri/build/freebsd-aarch64-build/bmake-install/share/mk', '--with-machine=amd64', '--without-filemon', '--prefix=/Users/simon/cheri/build/freebsd-aarch64-build/bmake-install']' returned non-zero exit status 1.
Fatal error (in target freebsd-aarch64): Command `nice /Users/simon/cheri/freebsd/tools/build/make.py -j16 buildworld -DDB_FROM_SRC -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH TARGET_ARCH=aarch64 TARGET=arm64 DEBUG_FLAGS=-g 'LOCAL_XTOOL_DIRS=lib/libnetbsd usr.sbin/makefs usr.bin/mkimg' -DWITHOUT_CLEAN -DWITH_TESTS -DWITHOUT_MAN -DWITHOUT_MAIL -DWITHOUT_DEBUG_FILES -DWITHOUT_PROFILE -DWITHOUT_OFED -DWITHOUT_GCC -DWITHOUT_CLANG -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -s -de` failed with non-zero exit code 1
```

**Comment by jrtc27** [comment]
This is a known issue with upstream FreeBSD. I assume you're running on an Arm-based Mac? For whatever reason that test segfaults. We've disabled it in CheriBSD, but in FreeBSD you'll need to edit contrib/bmake/unit-tests/Makefile and comment out the shell-ksh test.

**Comment by graymalkin** [comment]
Oh right, an Intel mac. Thanks for the headsup.

**Comment by jrtc27** [comment]
Ok, good to know it's not specific to Arm then, just the only context I've seen it
