### ISSUE TITLE
dbus-native issues on FreeBSD prevent pre-push hooks from passing

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribuild#288]
The dbus-native target appears to be broken on FreeBSD 13.1. This appears to be an issue with dbus itself not cheribuild as such, but this code seems to be being run even under `--test`.  I get a failure in:
```
./cheribuild.py -p __run_everything__ --clean --build --test --benchmark
```
Trimmed output:
```
-- Installing: /home/bed22/cheri/build/dbus-native-build/test-install-prefix/var/lib/dbus
-- Installing: /home/bed22/cheri/build/dbus-native-build/test-install-prefix/share/doc/dbus/examples/GetAllMatchRules.py
Running cmake install took 0.06816458702087402 seconds                                
Traceback (most recent call last):                                                
  File "/home/bed22/cheri/cheribuild/pycheribuild/__main__.py", line 267, in main                                           
    run_and_kill_children_on_exit(real_main)                                      
  File "/home/bed22/cheri/cheribuild/pycheribuild/processutils.py", line 788, in run_and_kill_children_on_exit
    fn()                                                                              
  File "/home/bed22/cheri/cheribuild/pycheribuild/__main__.py", line 256, in real_main
    target_manager.run(cheri_config, chosen_targets)                              
  File "/home/bed22/cheri/cheribuild/pycheribuild/targets.py", line 470, in run       
    target.execute(config)                                                        
  File "/home/bed22/cheri/cheribuild/pycheribuild/targets.py", line 131, in execute   
    self._do_run(config, msg="Built", func=lambda project: project.process())                                               
  File "/home/bed22/cheri/cheribuild/pycheribuild/targets.py", line 121, in _do_run                                         
    func(project)                                                                     
  File "/home/bed22/cheri/cheribuild/pycheribuild/targets.py", line 131, in <lambda>                                        
    self._do_run(config, msg="Built", func=lambda project: project.process())     
  File "/home/bed22/cheri/cheribuild/pycheribuild/projects/project.py", line 3298, in process
    self.install()                       
  File "/home/bed22/cheri/cheribuild/pycheribuild/projects/cross/dbus.py", line 52, in install
    rc_file = self.rootfs_dir / self.target_info.localbase / "etc/rc.d/dbus"    
  File "/home/bed22/cheri/cheribuild/pycheribuild/utils.py", line 154, in __get__ 
    val = self.func(instance)                                                         
  File "/home/bed22/cheri/cheribuild/pycheribuild/projects/project.py", line 2784, in rootfs_dir
    return self.target_info.get_rootfs_project().install_dir                      
  File "/home/bed22/cheri/cheribuild/pycheribuild/config/target_info.py", line 293, in get_rootfs_project
    return self._get_rootfs_project(xtarget.get_rootfs_target())                
  File "/home/bed22/cheri/cheribuild/pycheribuild/config/target_info.py", line 296, in _get_rootfs_project
    raise NotImplementedError("Should not be called for " + self.project.target)
NotImplementedError: Should not be called for dbus-native                             
Fatal error (in target dbus-native): Unhandled exception: Should not be called for dbus-native
```

**Comment by jrtc27** [comment]
Uh those Installing: lines should not exist for -p, sounds like something's missing a pretending check

**Comment by arichardson** [comment]
Looks like it's missing a `compiling_for_host()` check in the FreeBSD useradd logic. We may want to do it for native builds on cheribsd but only if it doesn't conflict with a future version installed from ports.

**Comment by brooksdavis** [comment]
Those were from a manual run, but the exception is the same.
